package com.inventory.service;

import com.inventory.dto.request.PurchaseOrderRequest;
import com.inventory.entity.*;
import com.inventory.repository.ProductRepository;
import com.inventory.repository.PurchaseOrderRepository;
import com.inventory.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Slf4j
public class AutoReorderService {

    private final ProductRepository productRepository;
    private final PurchaseOrderRepository purchaseOrderRepository;
    private final PurchaseOrderService purchaseOrderService;
    private final NotificationService notificationService;
    private final UserDetailsService userDetailsService;

    // --- SCHEDULED TASK (Background Bot) ---
    @Scheduled(fixedDelay = 3600000) 
    public void checkAndReorder() {
        // 1. Login as System Admin
        setupSystemContext();
        try {
            log.info("🤖 Auto-Reorder Bot: Scheduled scan started...");
            runBotLogic();
        } catch (Exception e) {
            log.error("Auto-Reorder Bot crashed", e);
        } finally {
            // 2. Logout to clean up thread
            SecurityContextHolder.clearContext();
        }
    }

    // --- MANUAL TRIGGER (Called by Controller) ---
    @Transactional
    public void runManualCheck() {
        log.info("🤖 Auto-Reorder Bot: Manual trigger by user");
        // No need to setup/clear context here; we use the logged-in user's context
        runBotLogic();
    }

    // --- SHARED LOGIC ---
    @Transactional
    protected void runBotLogic() {
        List<Product> products = productRepository.findByIsActiveTrue().stream()
                .filter(p -> Boolean.TRUE.equals(p.getAutoReorderEnabled()))
                .toList();

        int reorderedCount = 0;
        for (Product product : products) {
            if (product.isLowStock()) {
                boolean ordered = handleLowStock(product);
                if (ordered) reorderedCount++;
            }
        }
        log.info("Scan complete. Reordered {} items.", reorderedCount);
    }

    private boolean handleLowStock(Product product) {
        boolean hasPendingOrder = purchaseOrderRepository.findAll().stream()
                .filter(po -> po.getStatus() == PurchaseOrder.PurchaseOrderStatus.ORDERED 
                           || po.getStatus() == PurchaseOrder.PurchaseOrderStatus.PENDING
                           || po.getStatus() == PurchaseOrder.PurchaseOrderStatus.APPROVED)
                .flatMap(po -> po.getItems().stream())
                .anyMatch(item -> item.getProduct().getId().equals(product.getId()));

        if (hasPendingOrder) return false;

        Optional<ProductSupplier> supplierLink = product.getProductSuppliers().stream().findFirst();
        if (supplierLink.isEmpty()) {
            log.warn("Cannot auto-order {}: No supplier linked.", product.getSku());
            return false;
        }

        Supplier supplier = supplierLink.get().getSupplier();
        BigDecimal cost = supplierLink.get().getSupplierPrice() != null 
                ? supplierLink.get().getSupplierPrice() 
                : product.getCostPrice();

        PurchaseOrderRequest.Item item = new PurchaseOrderRequest.Item();
        item.setProductId(product.getId());
        item.setQuantity(product.getReorderQuantity());
        item.setUnitCost(cost);

        PurchaseOrderRequest request = new PurchaseOrderRequest();
        request.setSupplierId(supplier.getId());
        request.setItems(List.of(item));
        request.setNotes("🤖 Auto-generated by Inventory Bot");
        request.setExpectedDate(LocalDate.now().plusDays(7));

        try {
            PurchaseOrder po = purchaseOrderService.create(request);
            purchaseOrderService.updateStatus(po.getId(), PurchaseOrder.PurchaseOrderStatus.ORDERED);
            
            notificationService.notifyAdmins(
                Notification.NotificationType.INFO,
                "Auto-Order Placed",
                "Bot placed Order #" + po.getOrderNumber() + " for " + product.getName(),
                "PURCHASE_ORDER",
                po.getId()
            );
            return true;
        } catch (Exception e) {
            log.error("Failed to place auto-order for " + product.getSku(), e);
            return false;
        }
    }

    private void setupSystemContext() {
        try {
            String systemEmail = "admin@inventory.com"; 
            UserDetails userDetails = userDetailsService.loadUserByUsername(systemEmail);
            UsernamePasswordAuthenticationToken auth = new UsernamePasswordAuthenticationToken(
                    userDetails, null, userDetails.getAuthorities());
            SecurityContextHolder.getContext().setAuthentication(auth);
        } catch (Exception e) {
            log.error("Failed to set up System Security Context. Bot cannot run.", e);
        }
    }
}